name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context:
       push: true
       tags: tamarar/k8s-demo:latest

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Create target directory if it doesn't exist
      # - name: Create target directory
      #   run: |
      #     sudo mkdir -p /.minikube

      # Copy files (Add your file copy logic here)
      - name: Copy files
        run: |
          sudo mkdir -p /.minikube/profiles/minikube
          sudo cp .minikube/ca.crt /.minikube/ca.crt
          sudo cp .minikube/profiles/minikube/client.crt /.minikube/profiles/minikube/client.crt
          sudo cp .minikube/profiles/minikube/client.key /.minikube/profiles/minikube/client.key
          sudo mkdir -p $HOME/.kube
          sudo cp kubeconfig.yaml $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
        
      # Set up Kubernetes CLI
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1
        with:
          version: 'v1.27.4'

      # Configure kubectl to access your Kubernetes cluster
      # - name: Set up kubeconfig
      #   run: |
      #     export KUBECONFIG=$HOME/kubeconfig.yaml

      # - name: tmp
      #   run: |
      #     sudo kubectl config set-cluster minikube --server=https://5548-79-101-89-183.ngrok-free.app --certificate-authority=/.minikube/ca.crt
      #     sudo kubectl config set-credentials minikube --token=eyJhbGciOiJSUzI1NiIsImtpZCI6ImpwODdKdXNYeFBIOU1ORFpHYXVUa2Z0cUpGckU1UU1sWklkOWhVVk85ZUUifQ.eyJpc3MiOiJrdWJlcm5ldGVzL3NlcnZpY2VhY2NvdW50Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9uYW1lc3BhY2UiOiJkZWZhdWx0Iiwia3ViZXJuZXRlcy5pby9zZXJ2aWNlYWNjb3VudC9zZWNyZXQubmFtZSI6ImRlZmF1bHQtdG9rZW4iLCJrdWJlcm5ldGVzLmlvL3NlcnZpY2VhY2NvdW50L3NlcnZpY2UtYWNjb3VudC5uYW1lIjoiZGVmYXVsdCIsImt1YmVybmV0ZXMuaW8vc2VydmljZWFjY291bnQvc2VydmljZS1hY2NvdW50LnVpZCI6IjcxMjRmOGU3LTAxNjktNGUwYy1iNzY4LWY2MmU0MDA0MjM3NSIsInN1YiI6InN5c3RlbTpzZXJ2aWNlYWNjb3VudDpkZWZhdWx0OmRlZmF1bHQifQ.aF0pAmA2oZVJzMK8_iW2HRCZc4OSu9nLiIEd_DbwcqGGGV99ha3ZPpIdRsump1K97G225asyAOSLnExBvk7fWm1QSx2xup5TuCcb47XtAdyakFYiKqNQpSP0MMYw8BkJl8ZpyjkcEVUGc7BjyCGJDkrVIkyPuzT1kz4PSKwZB4QZUQG_5NCbk_HdkRHgal3igUH1set_L0YTOf4AF4eLwGLP4v-500XHfwN69HA6XfXjcYg1APbqxcfUmfhaCesLldhv2BZz9LxSiVjdL0L7mp-Qwj7igx3F0ajyHcMTWAoXqLPJLSXCzZLiIWZeCYE0vjNmdyrhPQnmmW6Z-71ycA
      #     sudo kubectl config set-context minikube --cluster=minikube --user=minikube
      #     sudo kubectl config use-context minikube
      #     sudo kubectl config view

      # Run kubectl command
      - name: Run kubectl command
        run: |
          kubectl get pods