name: Build and push Docker image to dockerhub

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context:
       push: true
       tags: tamarar/k8s-demo:latest

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Create target directory if it doesn't exist
      # - name: Create target directory
      #   run: |
      #     sudo mkdir -p /.minikube

      # Copy files (Add your file copy logic here)
      - name: Copy files
        run: |
          sudo mkdir -p /.minikube/profiles/minikube
          sudo cp .minikube/ca.crt /.minikube/ca.crt
          sudo cp .minikube/profiles/minikube/client.crt /.minikube/profiles/minikube/client.crt
          sudo cp .minikube/profiles/minikube/client.key /.minikube/profiles/minikube/client.key
          sudo mkdir -p $HOME/.kube
          sudo cp kubeconfig.yaml $HOME/.kube/config
          sudo chown $(id -u):$(id -g) $HOME/.kube/config
        
      # Set up Kubernetes CLI
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      # Configure kubectl to access your Kubernetes cluster
      # - name: Set up kubeconfig
      #   run: |
      #     export KUBECONFIG=$HOME/kubeconfig.yaml

      - name: tmp
        run: |
          sudo kubectl config use-context minikube
          sudo kubectl config view
          sudo kubectl auth whoami --insecure-skip-tls-verify

      # Run kubectl command
      - name: Run kubectl command
        run: |
          kubectl get pods -v=10 --insecure-skip-tls-verify