name: Build and push Docker image to dockerhub + Deploy to k8s cluster

on:
  push:
    branches: [ "main" ]
    
jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - name: Check out the repo
      uses: actions/checkout@v4

    - name: Login to dockerhub
      uses: docker/login-action@v3
      with:
       username: ${{ secrets.DOCKERHUB_USERNAME }}
       password: ${{ secrets.DOCKERHUB_TOKEN }}

    - name: Build and push to dockerhub
      uses: docker/build-push-action@v5
      with:
       context:
       push: true
       tags: tamarar/k8s-demo:latest

  deploy:
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Copy files
        run: |
          sudo mkdir -p /.minikube/profiles/minikube
          sudo cp .minikube/ca.crt /.minikube/ca.crt
          sudo cp .minikube/profiles/minikube/client.crt /.minikube/profiles/minikube/client.crt
          sudo cp .minikube/profiles/minikube/client.key /.minikube/profiles/minikube/client.key
          sudo mkdir -p $HOME/.kube
          sudo cp kubeconfig.yaml $HOME/.kube/config
        
      - name: Set up kubectl
        uses: azure/setup-kubectl@v1

      - name: Run kubectl command
        run: |
          kubectl get pods --insecure-skip-tls-verify